server {
    #listen 443 ssl http2;    # ssl http2
    listen 8080;
#     ssl_certificate /etc/nginx/certs/connector-ts.crt;
#     ssl_certificate_key /etc/nginx/certs/connector-ts.key;
#     ssl_client_certificate /etc/nginx/certs/ca.crt;
#     ssl_verify_client on;

    location /static/ {
        alias /var/www/static/;
    }

    location / {
        # 'django-app' — это имя сервиса из docker-compose.yml
        # '8000' — порт, на котором Gunicorn слушает ВНУТРИ своего контейнера
        proxy_pass http://connector-app:80;

        # Важные заголовки, чтобы Django понимал, откуда пришел запрос
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        # Прокидываем данные сертификата клиента (mTLS), если Django их ждет
#        proxy_set_header X-Client-DN $ssl_client_s_dn;
#        proxy_set_header X-Client-Verify $ssl_client_verify;
    }
}